name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install  # Change to yarn install if using Yarn

      - name: Build project
        run: npm run build  # Ensure this generates the correct output folder

      - name: Deploy using npm script
        run: npm run deploy  # This should push to gh-pages (configured in package.json)

      - name: Confirm Deployment URL
        run: echo "Deployment successful! Visit https://<your-username>.github.io/<repo-name>/"
